# Use postgres/example user/password credentials
version: '3.1'

volumes:
  database-data:

services:
  database:
    image: postgres
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file: ./.env.build

  calcom:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URI=${DATABASE_URL}
        - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL}
        - NEXT_PUBLIC_LICENSE_CONSENT=${NEXT_PUBLIC_LICENSE_CONSENT}
        - NEXT_PUBLIC_TELEMETRY_KEY=${NEXT_PUBLIC_TELEMETRY_KEY}
    restart: always
    ports:
      - 8080:3000
    env_file: ./.env.build
    image: calcom:latest
