FROM node:14 as builder

WORKDIR /calcom
ARG API_KEY_PREFIX
ARG EMAIL_FROM
ARG EMAIL_SERVER_HOST
ARG EMAIL_SERVER_PORT
ARG NEXT_PUBLIC_EMBED_LIB_URL
ARG NEXT_PUBLIC_WEBAPP_URL
ARG NEXT_PUBLIC_WEBSITE_URL
ARG NEXTAUTH_COOKIE_DOMAIN
ARG NEXTAUTH_URL
ARG NEXTAUTH_SECRET
ARG CALENDSO_ENCRYPTION_KEY
ARG DATABASE_URL
ARG EMAIL_SERVER_PASSWORD
ARG EMAIL_SERVER_USER
ARG GOOGLE_API_CREDENTIALS
ARG CRON_API_KEY
ARG ZOOM_CLIENT_ID
ARG ZOOM_CLIENT_SECRET
ARG NEXT_PUBLIC_LICENSE_CONSENT

ENV API_KEY_PREFIX=$API_KEY_PREFIX \
    EMAIL_FROM=$EMAIL_FROM \
    EMAIL_SERVER_HOST=$EMAIL_SERVER_HOST \
    EMAIL_SERVER_PORT=$EMAIL_SERVER_PORT \
    NEXT_PUBLIC_EMBED_LIB_URL=$NEXT_PUBLIC_EMBED_LIB_URL \
    NEXT_PUBLIC_WEBAPP_URL=$NEXT_PUBLIC_WEBAPP_URL \
    NEXT_PUBLIC_WEBSITE_URL=$NEXT_PUBLIC_WEBSITE_URL \
    NEXTAUTH_COOKIE_DOMAIN=$NEXTAUTH_COOKIE_DOMAIN \
    NEXTAUTH_URL=$NEXTAUTH_URL \
    NEXTAUTH_SECRET=$NEXTAUTH_SECRET \
    CALENDSO_ENCRYPTION_KEY=$CALENDSO_ENCRYPTION_KEY \
    DATABASE_URL=$DATABASE_URL \
    EMAIL_SERVER_PASSWORD=$EMAIL_SERVER_PASSWORD \
    EMAIL_SERVER_USER=$EMAIL_SERVER_USER \
    GOOGLE_API_CREDENTIALS=$GOOGLE_API_CREDENTIALS \
    CRON_API_KEY=$CRON_API_KEY \
    ZOOM_CLIENT_ID=$ZOOM_CLIENT_ID \
    ZOOM_CLIENT_SECRET=$ZOOM_CLIENT_SECRET \
    NEXT_PUBLIC_LICENSE_CONSENT=$NEXT_PUBLIC_LICENSE_CONSENT

COPY ./package.json ./yarn.lock ./turbo.json ./
COPY ./apps/web ./apps/web
COPY ./packages ./packages

RUN printenv

RUN yarn install --frozen-lockfile

RUN yarn build

FROM node:14 as runner

WORKDIR /calcom
ENV NODE_ENV production

RUN apt-get update && \
    apt-get -y install netcat && \
    rm -rf /var/lib/apt/lists/*

COPY ./package.json ./yarn.lock ./turbo.json ./
COPY --from=builder /calcom/node_modules ./node_modules
COPY --from=builder /calcom/packages ./packages
COPY --from=builder /calcom/apps/web ./apps/web
COPY --from=builder /calcom/packages/prisma/schema.prisma ./prisma/schema.prisma

EXPOSE 3000
CMD ["yarn", "start"]
